### ISSUE TITLE
目前动态ID已经无法识别并抽奖

### ISSUE THREAD

**Issue by gbxm** [InJeCTrL/BiliCommentLottery#1]
目前动态ID已经无法识别并抽奖，希望可以更新实现支持

**Comment by InJeCTrL** [comment]
目前BiliCLOnline已经更新了新的动态信息获取接口，本项目近期暂时没有维护，您可以替换使用BiliCLOnline！
https://injectrl.github.io/BiliCLOnline/
________________________________
From: gbxm ***@***.***>
Sent: Tuesday, May 16, 2023 7:15:32 PM
To: InJeCTrL/BiliCommentLottery ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [InJeCTrL/BiliCommentLottery] 目前动态ID已经无法识别并抽奖 (Issue #1)


目前动态ID已经无法识别并抽奖，希望可以更新实现支持

―

**Comment by InJeCTrL** [comment]
Fixed with d9e6abafc81d1109cf279cea69647cb0d0c59b78
